<?php return array(
    'root' => array(
        'name' => '__root__',
        'pretty_version' => 'dev-main',
        'version' => 'dev-main',
        'reference' => '131ec240b60154d9bc537366c1eb160118e1d594',
        'type' => 'library',
        'install_path' => __DIR__ . '/../../',
        'aliases' => array(),
        'dev' => true,
    ),
    'versions' => array(
        '__root__' => array(
            'pretty_version' => 'dev-main',
            'version' => 'dev-main',
            'reference' => '131ec240b60154d9bc537366c1eb160118e1d594',
            'type' => 'library',
            'install_path' => __DIR__ . '/../../',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mikehaertl/php-shellcommand' => array(
            'pretty_version' => '1.7.0',
            'version' => '1.7.0.0',
            'reference' => 'e79ea528be155ffdec6f3bf1a4a46307bb49e545',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mikehaertl/php-shellcommand',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mikehaertl/php-tmpfile' => array(
            'pretty_version' => '1.3.0',
            'version' => '1.3.0.0',
            'reference' => 'a5392bed91f67e2849a7cb24075d346468e1b1a8',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mikehaertl/php-tmpfile',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
        'mikehaertl/phpwkhtmltopdf' => array(
            'pretty_version' => '2.5.0',
            'version' => '2.5.0.0',
            'reference' => '17ee71341591415d942774eda2c98d8ba7ea9e90',
            'type' => 'library',
            'install_path' => __DIR__ . '/../mikehaertl/phpwkhtmltopdf',
            'aliases' => array(),
            'dev_requirement' => false,
        ),
    ),
);
